//Try catch

const numero1=20;

const numero3=40;


console.log(numero1);
try {
    console.log(numero2);
}catch (error){
    console.log(error);
}

console.log(numero3);